from .video_super_resolution import (
    NODE_CLASS_MAPPINGS as LAS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LAS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .volcengine_video_enhance import (
    NODE_CLASS_MAPPINGS as MEDIAKIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MEDIAKIT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **LAS_NODE_CLASS_MAPPINGS,
    **MEDIAKIT_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **LAS_NODE_DISPLAY_NAME_MAPPINGS,
    **MEDIAKIT_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
